Update MatMulInteger op parsing
ROCm/AMDMIGraphX pull request #2513
Opened 2023-12-05 13:43 UTC by gyulaz-htec

Add missing uint8 input support and zero point tensor support to [MatMulInteger](https://github.com/onnx/onnx/blob/main/docs/Operators.md#MatMulInteger).
For the detailed description see: https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/issues/2512

I've put this up as a draft because I ran into some problems, and I'm not sure if my solution is the best possible outcome:
* I tried to update `quant_dot` to accept uint8  type as well (it would be converted to int32 during lowering), but I got a rocBLAS error during gemm computation: `/code/AMDMIGraphX/src/targets/gpu/gemm_impl.cpp:109: operator(): rocblas_invoke: rocBLAS call failed with status 2`. Status 2 means not implemented. 
* Since I couldn't update `quant_dot` itself, I've updated `parse_matmul.cpp` where I tried to convert the input tensors to `int32_type`, to avoid overflows during the zero point computation.
This `int32_type` also fails when compiling against the `gpu` target with the same rocBLAs error (`/code/AMDMIGraphX/src/targets/gpu/gemm_impl.cpp:109: operator(): rocblas_invoke: rocBLAS call failed with status 2`).
For me it looks like `dot` only supports floating point input types for the gpu target, so I've changed the conversion from `int32_type` to `half_type` which produced the expected results.

2023-12-28 18:42 UTC, TedThemistokleous requested changes
Fix conflicts. Changes for this look good, and I think we're seeing this as part of some other models being read in with the missing uint8 support

2024-01-03 13:34 UTC, gyulaz-htec commented
> Fix conflicts. Changes for this look good, and I think we're seeing this as part of some other models being read in with the missing uint8 support

@TedThemistokleous I've fixed the conflicts also found the code path with uint8 inputs and no zero points is not covered with test, so I've added a verify test for that.

2024-01-03 14:24 UTC, kahmed10 approved these changes

2024-01-03 17:09 UTC, TedThemistokleous approved these changes

2024-01-03 19:37 UTC, merged