Dont paralellize par_transform when there isnt parallel stl enabled
ROCm/AMDMIGraphX pull request #2623
Opened 2024-01-10 23:27 UTC by pfultz2

2024-01-10 23:41 UTC, causten requested changes

2024-01-10 23:41 UTC, causten commented on src/include/migraphx/par.hpp
> +    return std::transform(first1, last1, first2, d_first, std::move(binary_op))
need a semicolon ;

2024-01-11 00:31 UTC, causten approved these changes
This fixes the problem

2024-01-11 04:00 UTC, umangyadav approved these changes

2024-01-11 14:29 UTC, merged