Fuse group convolution
ROCm/AMDMIGraphX pull request #2639
Opened 2024-01-12 22:28 UTC by pfultz2

2024-01-15 15:37 UTC, TedThemistokleous commented on src/simplify_algebra.cpp
> +            return;
Add test case to cover this return path.

2024-01-15 15:37 UTC, TedThemistokleous requested changes
Just add a test case to cover the axis != case in your apply. Otherwise LGTM

2024-01-15 16:05 UTC, umangyadav commented on src/simplify_algebra.cpp
> +            return;
Would this case occure at all ? All of the inputs to the concat must be convolution. It can't be empty

2024-02-01 20:10 UTC, CharlieL7 approved these changes
LGTM

2024-02-26 21:06 UTC, TedThemistokleous approved these changes
Just fix licensing now. LGTM too

2024-02-27 19:01 UTC, merged