Enable mlir by default for gemms with small K
ROCm/AMDMIGraphX pull request #2782
Opened 2024-02-15 23:32 UTC by pfultz2

2024-02-16 13:43 UTC, umangyadav approved these changes

2024-02-16 13:44 UTC, umangyadav requested changes

2024-02-16 13:44 UTC, umangyadav commented on src/targets/gpu/fuse_mlir.cpp
> -    mlir_mode mode =
This ENV Var can be removed and also need to update docs

2024-03-01 21:53 UTC, umangyadav approved these changes

2024-03-04 14:05 UTC, TedThemistokleous approved these changes

2024-03-04 14:21 UTC, TedThemistokleous commented
Fix the compile errors otherwise this makes sense

2024-03-06 18:41 UTC, merged