Suppress compilation warning about result not read
ROCm/AMDMIGraphX pull request #2841
Opened 2024-02-27 14:56 UTC by apwojcik

The official documentation allows us to use `std::ignore` for suppressing compilation warnings about return values not being read (even originally, it was designed to be used together with `std::tie`).
See more info here: https://en.cppreference.com/w/cpp/utility/tuple/ignore.

2024-02-27 15:18 UTC, pfultz2 approved these changes

2024-02-27 15:19 UTC, pfultz2 requested changes

2024-02-27 15:19 UTC, pfultz2 commented on test/ref/resize.cpp
> +    EXPECT(test::throws([&] { std::ignore = p.eval({}).back(); }));
Actually I think we can remove the call to `.back()` for this test. Its only checking that `eval` throws, it doesnt make sense to call `.back()` here.

2024-02-27 18:01 UTC, umangyadav approved these changes

2024-02-27 18:22 UTC, pfultz2 commented on test/ref/resize.cpp
> +    EXPECT(test::throws([&] { std::ignore = p.eval({}); }));
We shouldn't need the `std::ignore` as `p.eval` does not have the `no_discard` attribute.

2024-02-29 22:37 UTC, pfultz2 approved these changes

2024-02-29 23:02 UTC, merged