remove broken link
ROCm/AMDMIGraphX pull request #2857
Opened 2024-03-05 21:49 UTC by LisaDelaney

2024-03-05 23:03 UTC, causten requested changes

2024-03-05 23:03 UTC, causten commented on docs/driver.rst
> +An example command line combined with ``rocprof`` for tracing purposes is given below:
I count 7 backticks.  I think you missed or added one

2024-03-08 17:23 UTC, yhuiYH approved these changes

2024-03-08 20:24 UTC, causten approved these changes

2024-03-08 20:31 UTC, merged