Update Depends with correct HIP Runtime package name
ROCm/AMDMIGraphX pull request #2941
Opened 2024-04-03 05:42 UTC by arvindcheru

Proposed Changes:

- hip-rocclr package is deprecated
- This is replaced with latest package hip-runtime-amd.
- This change is to update the package depends of AMDMigraphx to the latest package name.

2024-04-03 14:24 UTC, umangyadav approved these changes

2024-04-03 16:05 UTC, causten approved these changes

2024-04-09 13:59 UTC, causten requested changes

2024-04-09 13:59 UTC, causten commented on CMakeLists.txt
> ++endif()
```suggestion
endif()
```

2024-04-09 14:04 UTC, arvindcheru commented on CMakeLists.txt
> ++endif()
Thank you for the support

2024-04-09 14:04 UTC, causten approved these changes

2024-04-09 23:30 UTC, merged