Update Stable Diffusion example
ROCm/AMDMIGraphX pull request #2951
Opened 2024-04-04 15:27 UTC by attila-dusnoki-htec

Update the Stable Diffusion 2.1 example to use torch gpu buffers.
Also there are some optimization with batching certain tensors.

The notebook is not updated, after it is done, i will mark it ready.

The unet time: ~85.7930 ms -> 77.4980 ms
The others are not really comparable, because there was no warmup, and those are run once.

2024-04-04 15:39 UTC, attila-dusnoki-htec commented
TODOs:
- [ ] Fix licensing
- [ ] Update jupyter notebook
- [ ] Extend it with fp16 (per-model to avoid unet nans e.g "--fp16" all or "--fp16 vae clip")
- [ ] Check if hip streams would make much difference instead of sync after copy and run

2024-04-07 18:17 UTC, causten commented on examples/diffusion/python_stable_diffusion_21/gradio_reqirements.txt
>  #####################################################################################
The file is spelt incorrectly.  You are missing the "u" in gradio_requirements.txt

2024-04-07 18:27 UTC, causten requested changes

2024-04-07 18:27 UTC, causten commented on examples/diffusion/python_stable_diffusion_21/gradio_reqirements.txt
> +# Copyright (c) 2015-2024 Advanced Micro Devices, Inc. All rights reserved.
Change from -f requirements.txt to -r requirements.txt

2024-04-09 13:37 UTC, causten approved these changes

2024-04-09 23:35 UTC, merged