Remove rocblas on windows
ROCm/AMDMIGraphX pull request #2966
Opened 2024-04-11 13:53 UTC by tvukovic-amd

Added MIGRAPHX_USE_ROCBLAS build option which is automatically ON on Windows and OFF on Linux.
When MIGRAPHX_USE_ROCBLAS is OFF, rocBLAS is removed on MIGraphX.

@apwojcik

2024-04-12 14:43 UTC, pfultz2 commented on CMakeLists.txt
> +endif()
This needs to be done before `rocm_create_package`.

2024-04-12 14:48 UTC, pfultz2 commented on src/targets/gpu/compile_miopen.cpp
> +#ifdef MIGRAPHX_USE_ROCBLAS
This should be defined as 1 or 0, so it should use `#if MIGRAPHX_USE_ROCBLAS`. Also I dont see you adding this define to cmake.

2024-04-12 14:49 UTC, pfultz2 commented on src/targets/gpu/fuse_mlir.cpp
> +#endif
We should not be changing how the environment variable works. This also disables miopen convolutions as well, which seems unrelated.

2024-04-12 14:53 UTC, pfultz2 commented on src/targets/gpu/fuse_ops.cpp
> +        match::find_matches(m, find_gemm_pointwise{});
This should not be moved here, it should stay in the list where it was at if rocblas is enabled.

2024-05-08 13:49 UTC, pfultz2 commented on src/targets/gpu/include/migraphx/gpu/context.hpp
> +#endif
You already ifdef this file so you shouldn't need an ifdef when including it.

2024-05-08 13:49 UTC, pfultz2 commented on src/targets/gpu/lowering.cpp
> +#endif
Same here, this doesnt need a ifdef.

2024-05-08 13:51 UTC, pfultz2 commented on src/targets/gpu/compile_miopen.cpp
> +#endif
Same here, the ifdef can be removed.

2024-05-08 13:54 UTC, pfultz2 commented on src/targets/gpu/CMakeLists.txt
> +    set(ROCBLAS_SRCS rocblas.cpp gemm_impl.cpp)
You already ifdef these sources, so we dont need to remove them from the list in cmake.

2024-05-08 15:19 UTC, tperry-amd commented
Please change the code to default the CMake variable to ON for now.

2024-05-08 15:21 UTC, tperry-amd requested changes

2024-05-08 15:21 UTC, tperry-amd commented on CMakeLists.txt
> +if(WIN32)
Let's change this code to default the variable to ON only right now.

2024-05-08 15:21 UTC, tperry-amd approved these changes

2024-05-09 20:56 UTC, merged