Limit parallelism for constant propagation cherry-pick
ROCm/AMDMIGraphX pull request #2992
Opened 2024-04-23 16:20 UTC by causten

This is a Cherry-pick of... Limit parallelism for constant propagation when parallel STL is not enabled (#2987) against the rocm-rel-6.1 branch.

2024-04-23 16:24 UTC, umangyadav approved these changes

2024-04-23 16:48 UTC, ahsan-ca approved these changes
LGTM. Thank you for the backport PR.

2024-04-23 17:13 UTC, pfultz2 requested changes
This needs to address the review feedback in the original PR.

2024-04-23 18:50 UTC, ahsan-ca commented
> This needs to address the review feedback in the original PR.

Addressed the review feedback in https://github.com/ROCm/AMDMIGraphX/pull/2993 and ported the changes to this PR.

2024-04-26 16:37 UTC, pfultz2 approved these changes

2024-05-02 19:31 UTC, vamovsik commented
Fix for https://ontrack-internal.amd.com/browse/SWDEV-447401

2024-05-02 19:31 UTC, merged