update rocMLIR SHA to pull in bug fix for invalid block size on Navi3x
ROCm/AMDMIGraphX pull request #3159
Opened 2024-06-06 12:02 UTC by umangyadav

2024-06-06 13:28 UTC, causten requested changes
I can't pull in this PR as is because rocMLIR branched.  You need to grab the commit off of their [rocm-rel-6.2](https://github.com/ROCm/rocMLIR/commits/release/rocm-rel-6.2) branch

2024-06-06 14:20 UTC, umangyadav commented
> I can't pull in this PR as is because rocMLIR branched. You need to grab the commit off of their [rocm-rel-6.2](https://github.com/ROCm/rocMLIR/commits/release/rocm-rel-6.2) branch

This can go in now

2024-06-06 14:22 UTC, causten approved these changes
rocMLIR merged the change using the same commit hash.  This is now valid

2024-06-07 15:29 UTC, causten approved these changes

2024-06-08 13:39 UTC, causten approved these changes

2024-06-08 13:39 UTC, merged