Controlnet example
ROCm/AMDMIGraphX pull request #3283
Opened 2024-07-17 00:23 UTC by richagadgil

2024-07-18 20:48 UTC, causten reviewed
1/2 MB png file uploaded in to a source code repo.  Is there any way to reduce/format the image to be under 100K ?

2024-07-18 23:52 UTC, richagadgil commented
> 1/2 MB png file uploaded in to a source code repo. Is there any way to reduce/format the image to be under 100K ?

Reduced to ~50K

2024-07-23 04:04 UTC, causten requested changes

2024-07-24 19:54 UTC, causten approved these changes

2024-07-24 19:54 UTC, merged