more batch sizes
ROCm/AMDMIGraphX pull request #3300
Opened 2024-07-23 23:24 UTC by richagadgil

2024-07-25 00:14 UTC, causten approved these changes

2024-07-25 04:56 UTC, kahmed10 requested changes
Please update the README as well, briefly explaining how to use the flag.

2024-07-25 04:58 UTC, kahmed10 commented
We may also need to update the gradio app to support more images in the UI.

2024-07-25 17:19 UTC, richagadgil commented
Updated README and Gradio App @kahmed10

2024-08-09 16:01 UTC, kahmed10 approved these changes

2024-08-09 22:28 UTC, merged