Move auto_contiguous before lowering
ROCm/AMDMIGraphX pull request #3343
Opened 2024-08-05 15:04 UTC by pfultz2

This should run before lowering. Running it earlier can cause contiguous to be incorrectly fused with mlir, which can cause mixed layout to be used when its not necessary.

2024-08-06 13:06 UTC, umangyadav approved these changes

2024-08-16 15:51 UTC, TedThemistokleous approved these changes

2024-08-16 15:51 UTC, TedThemistokleous commented
Fix CI otherwise looks good

2024-08-21 22:56 UTC, causten requested changes
We reran this twice and in both cases performance tanked on many models.  This can not be merged as is

2024-08-28 21:56 UTC, kahmed10 commented
@causten @pfultz2 inserting workaround to only move the pass if NHWC is enabled.

2024-08-29 21:08 UTC, merged