Rewrite 1x1 convolutions to gemm
ROCm/AMDMIGraphX pull request #3568
Opened 2024-10-29 14:31 UTC by pfultz2

This allows us to use rocblas for some gemms.

2024-10-29 18:44 UTC, shivadbhavsar commented on src/rewrite_dot.cpp
> +    return std::all_of(w.lens().begin() + 2, w.lens().end(), [](std::size_t i) { return i == 1; });
Might be worthwhile to have a 1x1x1 test case too since its allowed here to make sure it generalizes to the 3D case

2024-10-31 14:36 UTC, pfultz2 commented
Need to investigate the nasnet failure.

2024-10-31 16:31 UTC, CharlieL7 approved these changes
LGTM. Is this the only case where doing a convolution as a GEMM is beneficial? Technically any convolution can be done as a GEMM.

2024-11-11 15:39 UTC, pfultz2 commented
> LGTM. Is this the only case where doing a convolution as a GEMM is beneficial? Technically any convolution can be done as a GEMM.

For other sizes, we need to do windowing(and possibly some padding) which will require an extra copy when we reshape to a gemm, with tensors that are larger then the original input.

2024-12-18 21:53 UTC, causten commented
If you wrap the 1x1 with an env variable it could get merged

2025-02-19 16:39 UTC, kahmed10 commented on src/rewrite_dot.cpp
> +MIGRAPHX_DECLARE_ENV_VAR(MIGRAPHX_DISABLE_REWRITE_DOT);
Can we flip the logic on this for now? Until we know it's always faster or at least as fast as 1x1 convolutions.

2025-02-19 16:39 UTC, kahmed10 commented on src/rewrite_dot.cpp
> +MIGRAPHX_DECLARE_ENV_VAR(MIGRAPHX_DISABLE_REWRITE_DOT);
also needs documentation update

2025-03-07 22:47 UTC, amd-jmacaran commented
/AzurePipelines run

2025-03-13 14:21 UTC, causten requested changes
Need to resolve @kahmed10 comments.  The 1x1 conf to gemms can not be turned by default.  I want to merge the feature that would allow a user to turn on a flag that would force all 1x1 to gemms for performance testing, but as it is written this cant be merged

2025-03-18 19:21 UTC, causten commented
Still need to add an entry in to the docs/dev/env_vars.rst  for MIGRAPHX_ENABLE_REWRITE_DOT

2025-03-25 18:37 UTC, spolifroni-amd requested changes

2025-03-25 18:37 UTC, spolifroni-amd commented on docs/dev/env_vars.rst
> +Set to "1", "enable", "enabled", "yes", or "true" to use.
When you say "to use", it's not specific enough. It needs to be "to use rewrite dot" or "to enable dot rewriting". People might be putting this through a translator, so a detail like that is important.

2025-03-26 14:24 UTC, spolifroni-amd commented on docs/dev/env_vars.rst
> +Set to "1", "enable", "enabled", "yes", or "true" to use.
It shouldn't be "to use" for any of them then. It's ambiguous. The documentation should clarify things for the user since the main reason a user will consult documentation is if they need disambiguation and clarity.

This needs to be clarified. If this is a bigger project than this PR, then a documentation issue needs to be opened. But this needs to be fixed.

2025-03-26 22:08 UTC, causten commented on docs/dev/env_vars.rst
> +Set to "1", "enable", "enabled", "yes", or "true" to use.
Let's fix the "to use" in a separate PR

2025-03-26 22:10 UTC, causten approved these changes
Doc added, consistent with the existing format

2025-03-27 00:42 UTC, causten commented on docs/dev/env_vars.rst
> +Set to "1", "enable", "enabled", "yes", or "true" to use.
I opened https://github.com/ROCm/AMDMIGraphX/issues/3915 and would love help to make the working better

2025-03-27 18:57 UTC, spolifroni-amd approved these changes

2025-03-27 20:20 UTC, merged